### PR TITLE
First draft of Chapter 11

### PR DESCRIPTION
**Pull request by AustinRochford**
Parts of Chapter 11.  Two notes:

* This PyMC3 [pull request](https://github.com/pymc-devs/pymc3/pull/2637) will make ordinal regression simpler, so I'll wait on that.
* The book uses a nonstandard parametrization of the beta(-binomial) distribution, which requires some care (and reading the `R` `rethinking` source) to replicate, which is slowing me down a bit.

### CODE REVIEW

**Comment by aloctavodia** [comment]
This is really great!

If you need to deviate from the book in order to do something in a more _PyMC3onic way_, go for it! Just add a message explaining why you are doing things different from the book. 

One more thing, we are now using:
```python
plt.style.use(['seaborn-darkgrid', 'seaborn-colorblind'])
```
to set the plot's style, and for the colors we use  the notation `{'C0', 'C1', 'C2', ...}`

**Comment by aloctavodia** [comment]
BTW, let me know if you want me to merge this, or wait for more commits...

**Comment by AustinRochford** [comment]
I'll make those changes.  I'd say let's wait on merging this until I finish the overdispersed section at least.

**Comment by AustinRochford** [comment]
@aloctavodia I think this is good to merge now.  I'll continue working on the ordered logistic example when I have time, but it might be a little while.

**Pull request merged**
