### PR TITLE
Port Chapter 12

### LINKED ISSUE #8: Chapter 12 needs to be ported
We need contributors to work on Chapter 12

### PR DESCRIPTION
**Pull request by junpenglao**
Close #8. Also I added cc-by-4.0 licence to readme.

### CODE REVIEW

**Comment by aloctavodia** [comment]
Thanks a lot for taking the time to help with this. 
I will merged and then take a more careful look during the weekend :-)
FYI we have agreed with Richard McElreath to do not upload the solution to the problems, so not need to add the practice-part.

**Comment by junpenglao** [comment]
No problem ;-) I am organizing my next Bayesian class and planning to include some chapters from Rethinking. I will port also the last two chapters.

**Comment by aloctavodia** [comment]
Where are you going to give this class?  I am also preparing a new class for next year https://github.com/PrACiDa/EBAD (Spanish). 

Great to hear you are also going to port the last two chapters! @agustinaarroyuelo and I want to finish porting this book this year but we are with many things and no so much time, so thanks a lot.

**Comment by junpenglao** [comment]
Early next year - the details will depend on the format (3-day workshop or one-semester class). But I already included material from your book, Rethinking, and Bayesian Cognitive modeling ;-)

**Comment by aloctavodia** [comment]
Explosive mix ;-)

**Pull request merged**
