### PR TITLE
Finish Chapter 14

### LINKED ISSUE #10: Chapter 14 needs to be ported
We need contributors to work on Chapter 14

### PR DESCRIPTION
**Pull request by junpenglao**
Close #10

### CODE REVIEW

**Comment by aloctavodia** [comment]
Wow! this was much sooner than expected

**Comment by aloctavodia** [comment]
I just realized seaborn is imported but not used, can you fix it?

**Comment by junpenglao** [comment]
Sure - or do you want to squeeze it in #53?

**Comment by aloctavodia** [comment]
OK, I will add it to #53

**Comment by junpenglao** [comment]
Too late... I just sent a PR...

**Comment by aloctavodia** [comment]
LOL, perfect!

**Pull request merged**
