### PR TITLE
Chapter13

### LINKED ISSUE #9: Chapter 13 needs to be ported
We need contributors to work on Chapter 13

### PR DESCRIPTION
**Pull request by junpenglao**
Close #9.

### CODE REVIEW

**Comment by aloctavodia** [comment]
A couple of tips, in case you find them useful: 

* you don't need to this
```python
sns.set_color_codes()
C0, C1 = sns.color_palette()[:2]
```

you can just write something like this, and matplotlib will do the right job:
```python
plt.plot([1,3,4], 'C2')
```

for the _confidence region ellipses_ you can use statsmodels:
```python
from statsmodels.graphics.plot_grids import scatter_ellipse

scatter_ellipse(df, level=[0.1,0.3,0.5,0.8,0.99],
                varnames=['intercepts ', 'slopes '] + df.columns,
                plot_kwds={'color': 'C0', 'marker':'o'})
plt.xlim(1, 6)
plt.ylim(-3, 1);

```

**Comment by junpenglao** [comment]
Chapter 13 finish ;-) @aloctavodia

**Comment by aloctavodia** [comment]
Great! One question, why don't you use `scatter_ellipse` from statsmodels?

**Comment by junpenglao** [comment]
`scatter_ellipse` compute the mean and cov from the data (which use for scatter plot), but in this case the mean and cov is known or estimated from the posterior. What I end up doing is cherry picking some code from `scatter_ellipse`
 https://github.com/statsmodels/statsmodels/blob/master/statsmodels/graphics/plot_grids.py#L24

**Pull request merged**
